baseurl: /myblog
auto: true
menuitems:
    - name:          首页
      url:          /index.html
    - name:         分类
      url:          /categories.html
    - name:         标签
      url:          /tags.html
    - name:         归档
      url:           /archive.html          
    - name:         读书
      url:           /reading.html          
    - name:         工作
      url:           /working.html          
    - name:         关于
      url:           /about.html    
